// apps/dev-elements-angular/src/app/elements-preview/elements-preview.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-elements-preview',
  templateUrl: './elements-preview.component.html',
  styleUrls: ['./elements-preview.component.scss']
})
export class ElementsPreviewComponent implements OnInit {
  form!: FormGroup;
  config = [
    {
      tag: 'h1',
      innerText: true,
      defaultOptions: {
        innerText: 'h1h1h1h1'
      }
    }
  ];
  data = [
    {
      tag: 'ion-button',
      innerText: 'button',
      class: {
        a: true
      },
      attributes: {
        mode: 'ios'
      },
      style: {
        minWidth: '200px'
      }
    },
    {
      tag: 'h1'
    },
    {
      tag: 'div',
      children: [
        {
          tag: 'h1',
          innerText: 'true'
        }
      ]
    },
    {
      tag: 'aiao-img',
      attributes: {
        src: 'http://image-demo.oss-cn-hangzhou.aliyuncs.com/example.jpg'
      }
    }
  ];

  constructor(private formBuilder: FormBuilder) {}

  ngOnInit(): void {
    this.form = this.formBuilder.group({
      config: [this.config],
      elements: [this.data]
    });
    this.form.valueChanges.subscribe(d => {
      console.log('valueChanges', d);
    });
  }
}

<ion-header translucent>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-menu-button></ion-menu-button>
    </ion-buttons>
    <ion-title>Elements Preview</ion-title>
  </ion-toolbar>
</ion-header>
<ion-content fullscreen>
  <div class="container">
    <form class="editor" [formGroup]="form">
      <aiao-code-editor class="item" language="json" formControlName="elements"></aiao-code-editor>
      <aiao-code-editor class="item" language="json" formControlName="config"></aiao-code-editor>
    </form>
    <aiao-elements-preview id="preview" [value]="form.value.elements" [config]="form.value.config"></aiao-elements-preview>
  </div>
</ion-content>

// apps/dev-elements-vue/src/app/views/elements-preview.vue
<template>
  <div>
    <ion-header translucent>
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-menu-button></ion-menu-button>
        </ion-buttons>
        <ion-title>Elements Preview</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content fullscreen>
      <div class="container">
        <form class="editor">
          <aiao-code-editor
            class="editor-item"
            language="json"
            :value="data"
            @change="formChange($event)"
          ></aiao-code-editor>
          <aiao-code-editor class="editor-item" language="json" :value="config"></aiao-code-editor>
        </form>
        <aiao-elements-preview id="preview" :value="data" :config="config"></aiao-elements-preview>
      </div>
    </ion-content>
  </div>
</template>

<style scoped>
.editor {
  width: 50%;
  height: 100%;
}

.editor-item {
  width: 100%;
  height: 50%;
}

#preview {
  flex: 1;
  margin-left: 20px;
}

.container {
  display: flex;
  width: 100%;
  height: 100%;
}
</style>

<script>
import { defineComponent } from 'vue';
const config = [
  {
    tag: 'h1',
    innerText: true,
    defaultOptions: {
      innerText: 'h1h1h1h1'
    }
  }
];
const data = [
  {
    tag: 'ion-button',
    innerText: 'button',
    class: {
      a: true
    },
    attributes: {
      mode: 'ios'
    },
    style: {
      minWidth: '200px'
    }
  },
  {
    tag: 'h1'
  },
  {
    tag: 'div',
    children: [
      {
        tag: 'h1',
        innerText: 'true'
      }
    ]
  },
  {
    tag: 'aiao-img',
    attributes: {
      src: 'http://image-demo.oss-cn-hangzhou.aliyuncs.com/example.jpg'
    }
  }
];
export default defineComponent({
  data: () => ({ config, data }),
  methods: {
    formChange: e => {
      console.log(e.data);
    }
  }
});
</script>
