// libs/elements-react/src/lib/react-component-lib/createComponent.tsx
import React from 'react';

import { HTMLStencilElement } from '@stencil/core/internal/stencil-public-runtime';

import { attachProps, createForwardRef, dashToPascalCase, isCoveredByReact, mergeRefs } from './utils';

interface StencilReactInternalProps<ElementType> extends React.HTMLAttributes<ElementType> {
  forwardedRef?: React.RefObject<ElementType>;
  ref?: React.Ref<any>;
}

export const createReactComponent = <
  PropType,
  ElementType extends HTMLStencilElement,
  ContextStateType = {},
  ExpandedPropsTypes = {}
>(
  tagName: string,
  ReactComponentContext?: React.Context<ContextStateType>,
  manipulatePropsFunction?: (
    originalProps: StencilReactInternalProps<ElementType>,
    propsToPass: any,
  ) => ExpandedPropsTypes,
) => {
  const displayName = dashToPascalCase(tagName);

  const ReactComponent = class extends React.Component<StencilReactInternalProps<ElementType>> {
    componentEl!: ElementType;

    setComponentElRef = (element: ElementType) => {
      this.componentEl = element;
    };

    constructor(props: StencilReactInternalProps<ElementType>) {
      super(props);
    }

    componentDidMount() {
      this.componentDidUpdate(this.props);
    }

    componentDidUpdate(prevProps: StencilReactInternalProps<ElementType>) {
      attachProps(this.componentEl, this.props, prevProps);
    }

    render() {
      const { children, forwardedRef, style, className, ref, ...cProps } = this.props;

      let propsToPass = Object.keys(cProps).reduce((acc, name) => {
        if (name.indexOf('on') === 0 && name[2] === name[2].toUpperCase()) {
          const eventName = name.substring(2).toLowerCase();
          if (isCoveredByReact(eventName)) {
            (acc as any)[name] = (cProps as any)[name];
          }
        }
        return acc;
      }, {});

      if (manipulatePropsFunction) {
        propsToPass = manipulatePropsFunction(this.props, propsToPass);
      }

      const newProps: StencilReactInternalProps<ElementType> = {
        ...propsToPass,
        ref: mergeRefs(forwardedRef!, this.setComponentElRef),
        style,
      };




      return React.createElement(tagName, newProps, children);
    }

    static get displayName() {
      return displayName;
    }
  };

  // If context was passed to createReactComponent then conditionally add it to the Component Class
  if (ReactComponentContext) {
    ReactComponent.contextType = ReactComponentContext;
  }

  return createForwardRef<PropType, ElementType>(ReactComponent, displayName);
};

// integration/stencil-toolkit-nx/libs/react-lib/src/lib/components/createComponent.tsx
import React from 'react';
import ReactDom from 'react-dom';

import { attachProps, createForwardRef, dashToPascalCase, isCoveredByReact } from './utils';

interface IonicReactInternalProps<ElementType> extends React.HTMLAttributes<ElementType> {
  forwardedRef?: React.Ref<ElementType>;
  href?: string;
  routerLink?: string;
  ref?: React.Ref<any>;
  // routerDirection?: RouterDirection;
}

export const createReactComponent = <PropType, ElementType>(tagName: string, routerLinkComponent = false) => {
  const displayName = dashToPascalCase(tagName);
  const ReactComponent = class extends React.Component<IonicReactInternalProps<PropType>> {
    // context!: React.ContextType<typeof NavContext>;

    constructor(props: IonicReactInternalProps<PropType>) {
      super(props);
    }

    componentDidMount() {
      this.componentDidUpdate(this.props);
    }

    componentDidUpdate(prevProps: IonicReactInternalProps<PropType>) {
      const node = ReactDom.findDOMNode(this) as HTMLElement;
      attachProps(node, this.props, prevProps);
    }

    // private handleClick = (e: React.MouseEvent<PropType>) => {
    //   const { routerLink, routerDirection } = this.props;
    //   if (routerLink !== undefined) {
    //     e.preventDefault();
    //     this.context.navigate(routerLink, routerDirection);
    //   }
    // };

    render() {
      const { children, forwardedRef, style, className, ref, ...cProps } = this.props;

      const propsToPass = Object.keys(cProps).reduce((acc, name) => {
        if (name.indexOf('on') === 0 && name[2] === name[2].toUpperCase()) {
          const eventName = name.substring(2).toLowerCase();
          if (isCoveredByReact(eventName)) {
            (acc as any)[name] = (cProps as any)[name];
          }
        }
        return acc;
      }, {});

      const newProps: IonicReactInternalProps<PropType> = {
        ...propsToPass,
        ref: forwardedRef,
        style
      };

      if (routerLinkComponent) {
        if (this.props.routerLink && !this.props.href) {
          newProps.href = this.props.routerLink;
        }
        // if (newProps.onClick) {
        //   const oldClick = newProps.onClick;
        //   newProps.onClick = (e: React.MouseEvent<PropType>) => {
        //     oldClick(e);
        //     if (!e.defaultPrevented) {
        //       this.handleClick(e);
        //     }
        //   };
        // } else {
        //   newProps.onClick = this.handleClick;
        // }
      }

      return React.createElement(tagName, newProps, children);
    }

    static get displayName() {
      return displayName;
    }

    // static get contextType() {
    //   return NavContext;
    // }
  };
  return createForwardRef<PropType, ElementType>(ReactComponent, displayName);
};
