// apps/dev-elements-vue/src/app/views/elements-editor.vue
<template>
  <div>
    <ion-header translucent>
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-menu-button></ion-menu-button>
        </ion-buttons>
        <ion-title>Code Editor</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content fullscreen>
      <form>
        <aiao-elements-editor :value="data" :config="config"></aiao-elements-editor>
      </form>
    </ion-content>
  </div>
</template>

<style scoped>
aiao-code-editor.form {
  width: 100%;
  height: 100%;
}
aiao-code-editor {
  height: 500px !important;
}
</style>

<script>
import { defineComponent } from 'vue';

const config = [
  {
    tag: 'h1',
    innerText: true,
    defaultOptions: {
      innerText: 'h1h1h1h1'
    }
  }
];
const data = [
  {
    tag: 'ion-button',
    innerText: 'button',
    class: {
      a: true
    },
    attributes: {
      mode: 'ios'
    },
    style: {
      minWidth: '200px'
    }
  },
  {
    tag: 'h1'
  },
  {
    tag: 'div',
    children: [
      {
        tag: 'h1',
        innerText: 'true'
      }
    ]
  },
  {
    tag: 'aiao-img',
    attributes: {
      src: 'http://image-demo.oss-cn-hangzhou.aliyuncs.com/example.jpg'
    }
  }
];

export default defineComponent({
  data: () => ({ config, data })
});
</script>

// apps/dev-elements-angular/src/app/elements-editor/elements-editor.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-elements-editor',
  templateUrl: './elements-editor.component.html',
  styleUrls: ['./elements-editor.component.scss']
})
export class ElementsEditorComponent implements OnInit {
  form: FormGroup;
  config = [
    {
      tag: 'h1',
      innerText: true,
      defaultOptions: {
        innerText: 'h1h1h1h1'
      }
    }
  ];
  data = [
    {
      tag: 'ion-button',
      innerText: 'button',
      class: {
        a: true
      },
      attributes: {
        mode: 'ios'
      },
      style: {
        minWidth: '200px'
      }
    },
    {
      tag: 'h1'
    },
    {
      tag: 'div',
      children: [
        {
          tag: 'h1',
          innerText: 'true'
        }
      ]
    },
    {
      tag: 'aiao-img',
      attributes: {
        src: 'http://image-demo.oss-cn-hangzhou.aliyuncs.com/example.jpg'
      }
    }
  ];
  constructor(private formBuilder: FormBuilder) {
    this.form = this.formBuilder.group({
      elements: [this.data]
    });
  }

  ngOnInit(): void {
    this.form.valueChanges.subscribe(d => {
      console.log('valueChanges', d);
    });
  }
}

<ion-header translucent>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-menu-button></ion-menu-button>
    </ion-buttons>
    <ion-title>Code Editor</ion-title>
  </ion-toolbar>
</ion-header>
<ion-content fullscreen>
  <form [formGroup]="form">
    <aiao-elements-editor formControlName="elements" [config]="config"></aiao-elements-editor>
  </form>
</ion-content>
