// integration/stencil-toolkit-nx/apps/react/src/app/app.tsx
import React from 'react';

import './app.scss';
import { MyComponent } from '@stencil-toolkit-nx/react-lib';

export const App = () => {
  /*
   * Replace the elements below with your own.
   *
   * Note: The corresponding styles are in the ./${fileName}.${style} file.
   */
  return <MyComponent first="Stencil" last="'Don't call me a framework' JS"></MyComponent>;
};

export default App;

// integration/stencil-toolkit-nx/apps/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'stencil-toolkit-nx-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular';
}

<my-component first="Stencil" last="'Don't call me a framework' JS"></my-component>
