// apps/dev-elements-react/src/app/code-editor/code-editor.tsx
import './code-editor.scss';

import React from 'react';

import { AiaoCodeEditor } from '@aiao/elements-react';
import { IonButtons, IonContent, IonHeader, IonMenuButton, IonPage, IonTitle, IonToolbar } from '@ionic/react';

export const CodeEditor: React.FC = () => {
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonButtons slot="start">
            <IonMenuButton />
          </IonButtons>
          <IonTitle>Code Editor</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen scroll-events="false" scroll-x="false" scroll-y="false">
        <AiaoCodeEditor baseUrl="assets/monaco" language="typescript" value="const a = 'react';"></AiaoCodeEditor>
      </IonContent>
    </IonPage>
  );
};

export default CodeEditor;

// apps/dev-elements-vue-new/src/views/code-editor.vue
<template>
  <ion-page>
    <ion-header translucent>
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-menu-button></ion-menu-button>
        </ion-buttons>
        <ion-title>Code Editor</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content fullscreen>
      <aiao-code-editor language="json" :value="data"></aiao-code-editor>
    </ion-content>
  </ion-page>
</template>

<script lang="ts">
import { defineComponent, reactive } from 'vue';
import { AiaoCodeEditor } from '@aiao/elements-vue';
const data = [
  {
    tag: 'ion-button',
    innerText: 'button',
    class: {
      a: true
    },
    attributes: {
      mode: 'ios'
    },
    style: {
      minWidth: '200px'
    }
  },
  {
    tag: 'h1'
  },
  {
    tag: 'div',
    children: [
      {
        tag: 'h1',
        innerText: 'true'
      }
    ]
  },
  {
    tag: 'aiao-img',
    attributes: {
      src: 'http://image-demo.oss-cn-hangzhou.aliyuncs.com/example.jpg'
    }
  }
];
import { IonButtons, IonContent, IonHeader, IonMenuButton, IonPage, IonTitle, IonToolbar } from '@ionic/vue';

export default defineComponent({
  components: {
    AiaoCodeEditor,
    IonButtons,
    IonContent,
    IonHeader,
    IonPage,
    IonToolbar
  },
  setup() {
    return { data };
  }
});
</script>
<style scoped></style>
