// apps/dev-elements-vue/src/app/views/code-editor.vue
<template>
  <div>
    <ion-header translucent>
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-menu-button></ion-menu-button>
        </ion-buttons>
        <ion-title>Code Editor</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content fullscreen>
      <aiao-code-editor base-url="assets/monaco" language="json"></aiao-code-editor>
    </ion-content>
  </div>
</template>

<style scoped>
aiao-code-editor.form {
  width: 100%;
  height: 100%;
}
aiao-code-editor {
  height: 500px !important;
}
</style>

<script>
import { defineComponent } from 'vue';

export default defineComponent({});
</script>

// apps/dev-elements-angular/src/app/code-editor/code-editor.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-elements-code-editor',
  templateUrl: './code-editor.component.html',
  styleUrls: ['./code-editor.component.scss']
})
export class ElementsCodeEditorComponent implements OnInit {
  form: FormGroup;
  constructor(private formBuilder: FormBuilder) {
    this.form = this.formBuilder.group({
      json: {
        b: 1
      }
    });
  }

  ngOnInit(): void {
    this.form.valueChanges.subscribe(d => {
      console.log('valueChanges', d);
    });
  }
}

<ion-header translucent>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-menu-button></ion-menu-button>
    </ion-buttons>
    <ion-title>Code Editor</ion-title>
  </ion-toolbar>
</ion-header>
<ion-content fullscreen>
  <form [formGroup]="form">
    <aiao-code-editor base-url="assets/monaco" formControlName="json" language="json"></aiao-code-editor>
  </form>
</ion-content>
