// apps/dev-elements-react/src/app/code-editor/code-editor.tsx
import './code-editor.scss';

import React from 'react';

import { AiaoCodeEditor } from '@aiao/elements-react';

export const CodeEditor = () => {
  return (
    <AiaoCodeEditor
      base-url="https://cdn.jsdelivr.net/npm/monaco-editor@0.19.2/min"
      language="typescript"
      value="const a = 'react';"
    ></AiaoCodeEditor>
  );
};

export default CodeEditor;

// integration/elements/src/app/code-editor/code-editor.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-elements-code-editor',
  templateUrl: './code-editor.component.html',
  styleUrls: ['./code-editor.component.scss']
})
export class ElementsCodeEditorComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<aiao-code-editor base-url="assets/monaco" id="editor" language="typescript" value="const a=123;"></aiao-code-editor>
